name: Daily Repository Sync

on:
  schedule:
    # 每天凌晨3点运行 (UTC时间，对应北京时间11点)
    - cron: '0 3 * * *'
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  sync:
    name: Sync Repository
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config --global user.name "10000ge10000"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      
      - name: Sync with upstream
        run: |
          # 请将下面的URL替换为你想要同步的上游仓库地址
          # 例如：https://github.com/original-author/pansou-ui.git
          git remote add upstream https://github.com/original-author/pansou-ui.git
          git fetch upstream
          git checkout main  # 如果你的默认分支不是main，请修改此处
          git merge upstream/main
          git push origin main
